version: '3'

services:
  bot_dilmuss:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - celery_worker_dilmuss
      - celery_beat_dilmuss

  celery_worker_dilmuss:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis_dilmuss

  celery_beat_dilmuss:
    build: .
    command: celery -A tasks beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis_dilmuss

  redis_dilmuss:
    container_name: redis_dilmuss
    image: redis:latest
