version: '3'

services:
  bot_dilmuss:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - celery_worker_dilmuss
      - celery_beat_dilmuss

  celery_worker_dilmuss:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis_dilmuss:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_dilmuss:6379/0
    depends_on:
      - redis_dilmuss

  celery_beat_dilmuss:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks beat --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis_dilmuss:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_dilmuss:6379/0
    depends_on:
      - redis_dilmuss

  redis_dilmuss:
    container_name: redis_dilmuss
    image: redis:latest
